import { ComponentProps, FC } from 'react'

declare module 'lucide-react' {
  export type LucideIcon = FC<ComponentProps<'svg'>>
  
  export const MessageSquare: LucideIcon
  export const BarChart3: LucideIcon
  export const Wallet: LucideIcon
  export const Settings: LucideIcon
  export const Zap: LucideIcon
  export const Shield: LucideIcon
  export const ArrowRight: LucideIcon
  export const Sparkles: LucideIcon
  export const Menu: LucideIcon
  export const X: LucideIcon
  export const ChevronDown: LucideIcon
  export const ExternalLink: LucideIcon
  export const Copy: LucideIcon
  export const Check: LucideIcon
  export const Activity: LucideIcon
  export const TrendingUp: LucideIcon
  export const TrendingDown: LucideIcon
  export const DollarSign: LucideIcon
  export const Users: LucideIcon
  export const Percent: LucideIcon
  export const MoreHorizontal: LucideIcon
  export const Search: LucideIcon
  export const Filter: LucideIcon
  export const Download: LucideIcon
  export const RefreshCw: LucideIcon
  export const Calendar: LucideIcon
  export const Clock: LucideIcon
  export const AlertTriangle: LucideIcon
  export const Info: LucideIcon
  export const CheckCircle: LucideIcon
  export const XCircle: LucideIcon
  export const Eye: LucideIcon
  export const EyeOff: LucideIcon
  export const Lock: LucideIcon
  export const Unlock: LucideIcon
  export const Key: LucideIcon
  export const Globe: LucideIcon
  export const Link: LucideIcon
  export const Mail: LucideIcon
  export const Phone: LucideIcon
  export const MapPin: LucideIcon
  export const Home: LucideIcon
  export const User: LucideIcon
  export const Users2: LucideIcon
  export const Bell: LucideIcon
  export const BellOff: LucideIcon
  export const Heart: LucideIcon
  export const Star: LucideIcon
  export const Bookmark: LucideIcon
  export const Share: LucideIcon
  export const Send: LucideIcon
  export const Reply: LucideIcon
  export const Forward: LucideIcon
  export const Edit: LucideIcon
  export const Edit2: LucideIcon
  export const Edit3: LucideIcon
  export const Trash: LucideIcon
  export const Trash2: LucideIcon
  export const Save: LucideIcon
  export const Upload: LucideIcon
  export const FileText: LucideIcon
  export const File: LucideIcon
  export const Folder: LucideIcon
  export const FolderOpen: LucideIcon
  export const Image: LucideIcon
  export const Video: LucideIcon
  export const Music: LucideIcon
  export const Play: LucideIcon
  export const Pause: LucideIcon
  export const Stop: LucideIcon
  export const SkipBack: LucideIcon
  export const SkipForward: LucideIcon
  export const Repeat: LucideIcon
  export const Shuffle: LucideIcon
  export const Volume: LucideIcon
  export const Volume1: LucideIcon
  export const Volume2: LucideIcon
  export const VolumeX: LucideIcon
  export const Mic: LucideIcon
  export const MicOff: LucideIcon
  export const Camera: LucideIcon
  export const CameraOff: LucideIcon
  export const Wifi: LucideIcon
  export const WifiOff: LucideIcon
  export const Bluetooth: LucideIcon
  export const Battery: LucideIcon
  export const BatteryLow: LucideIcon
  export const Power: LucideIcon
  export const PowerOff: LucideIcon
  export const Sun: LucideIcon
  export const Moon: LucideIcon
  export const CloudRain: LucideIcon
  export const Cloud: LucideIcon
  export const CloudSnow: LucideIcon
  export const Thermometer: LucideIcon
  export const Wind: LucideIcon
  export const Umbrella: LucideIcon
  export const Car: LucideIcon
  export const Train: LucideIcon
  export const Plane: LucideIcon
  export const Ship: LucideIcon
  export const Bicycle: LucideIcon
  export const Bus: LucideIcon
  export const Truck: LucideIcon
  export const Fuel: LucideIcon
  export const ShoppingCart: LucideIcon
  export const ShoppingBag: LucideIcon
  export const CreditCard: LucideIcon
  export const Coins: LucideIcon
  export const Banknote: LucideIcon
  export const PiggyBank: LucideIcon
  export const TrendingUp: LucideIcon
  export const TrendingDown: LucideIcon
  export const BarChart: LucideIcon
  export const LineChart: LucideIcon
  export const PieChart: LucideIcon
  export const Target: LucideIcon
  export const Award: LucideIcon
  export const Trophy: LucideIcon
  export const Medal: LucideIcon
  export const Gift: LucideIcon
  export const Package: LucideIcon
  export const Box: LucideIcon
  export const Archive: LucideIcon
  export const Inbox: LucideIcon
  export const Outbox: LucideIcon
  export const Tag: LucideIcon
  export const Tags: LucideIcon
  export const Flag: LucideIcon
  export const Bookmark: LucideIcon
  export const Pin: LucideIcon
  export const Paperclip: LucideIcon
  export const Scissors: LucideIcon
  export const Ruler: LucideIcon
  export const Palette: LucideIcon
  export const Brush: LucideIcon
  export const Pen: LucideIcon
  export const PenTool: LucideIcon
  export const Type: LucideIcon
  export const AlignLeft: LucideIcon
  export const AlignCenter: LucideIcon
  export const AlignRight: LucideIcon
  export const AlignJustify: LucideIcon
  export const Bold: LucideIcon
  export const Italic: LucideIcon
  export const Underline: LucideIcon
  export const Strikethrough: LucideIcon
  export const Code: LucideIcon
  export const Code2: LucideIcon
  export const Terminal: LucideIcon
  export const Database: LucideIcon
  export const Server: LucideIcon
  export const Monitor: LucideIcon
  export const Smartphone: LucideIcon
  export const Tablet: LucideIcon
  export const Laptop: LucideIcon
  export const Mouse: LucideIcon
  export const Keyboard: LucideIcon
  export const Headphones: LucideIcon
  export const Speaker: LucideIcon
  export const Printer: LucideIcon
  export const Scanner: LucideIcon
  export const Gamepad: LucideIcon
  export const Gamepad2: LucideIcon
  export const Joystick: LucideIcon
  export const Cpu: LucideIcon
  export const HardDrive: LucideIcon
  export const MemoryStick: LucideIcon
  export const Usb: LucideIcon
  export const Cable: LucideIcon
  export const Plug: LucideIcon
  export const PlugZap: LucideIcon
  export const Zap: LucideIcon
  export const ZapOff: LucideIcon
  export const Flash: LucideIcon
  export const Flashlight: LucideIcon
  export const FlashlightOff: LucideIcon
  export const Lightbulb: LucideIcon
  export const LightbulbOff: LucideIcon
} 